helmDefaults:
  wait: true
  atomic: true
  timeout: 300

repositories:
   - url: harbor.quckoo.net/education
     name: educationtask-chart/educationtask
     username: {{ .Values.HARBOR_LOGIN }}
     password: {{ .Values.HARBOR_PASSWORD }}
     oci: true

environments:
  development:
  production:

releases:
  - name: application
    namespace: {{ .Values.NS }}
    createNamespace: false
    chart: educationtask-chart/educationtask
    values:
      - imagePull:
          credentials: {{ .Values.IMAGE_PULL_SECRET_CREDENTIALS_BASE64 }}
          secretName: {{ .Values.SECERT_NAME }}
      - imagePullSecrets: 
          - name: {{ .Values.SECERT_NAME }}
      - image:
          tag: {{ .Values.IMAGE_TAG }}